### PR TITLE
[cc65] Fixed internal representation of calculated constant results

### LINKED ISSUE #1310: surprising constant expression evaluation
`255 * 255 == -511` is false. I guess this is standard-compliant, since it involves signed integer overflow, but it would be nicer if it (1) gave a warning (2) also evaluated to true, since `int x = 255; x * x == -511` and `int y = 255 * 255; y == -511;` are both true.

```
#include <stdio.h>

static unsigned char failures = 0;

int main (void)
{
    const int two_fifty_five = 255;
    const int two_fifty_five_squared = 255 * 255;

    if (255 * 255 != -511) {
        fprintf (stderr, "Expected 255 * 255 == -511, got: %d\n", 255 * 255);
        failures++;
    }
    if (two_fifty_five * two_fifty_five != -511) {
        fprintf (stderr, "Expected two_fifty_five * two_fifty_five == -511, got: %d\n",
                 two_fifty_five * two_fifty_five);
        failures++;
    }
    if (two_fifty_five_squared != -511) {
        fprintf (stderr, "Expected two_fifty_five_squared == -511, got: %d\n",
                 two_fifty_five_squared);
        failures++;
    }
    printf ("failures: %u\n", failures);
    return failures;
}
```

Gives:
```
Expected 255 * 255 == -511, got: -511
failures: 1
```

### PR DESCRIPTION
**Pull request by acqn**
- [X] Fixed #1310 as well as some more cases.
Note: The numeric constant results of unary and binary calculations are stored inside `Expr->IVal`, which are as expected to be mathematically correct after being converted to its type. On the other hand, the offsets of expressions are not converted.
- [X] Fixed a bug that pointer subtraction results from two absolute addresses are calculated as `unsigned long`.
- [X] Test cases for the issues above.

### CODE REVIEW

File: src/cc65/expr.c [hunk 1]
```diff
@@ -2501,6 +2501,37 @@ static void hie_internal (const GenDesc* Ops,   /* List of generators */
                 }
             }
 
+            /* Limit the calculated value to the range of its type */
+            switch (GetUnderlyingTypeCode (Expr->Type)) {
+                case T_INT:
+                case T_SHORT:
+                    Expr->IVal = (signed short)Expr->IVal;
```
Comment (jmr) [inline src/cc65/expr.c:2508]: Nit: Maybe `CHECK (sizeof (short) == 2)`, unless this is a global assumption.

**Comment by jmr** [comment]
What about unary operators? Can't `~` and `-` make unwanted high bits? (Maybe this is already handled somewhere for all I know.)

There are tests in #1310 that will need to be moved to `val/` when that is merged.  The tests from #1312 that were `#if 0`-ed out should also be enabled.  https://github.com/cc65/cc65/pull/1312/files

File: src/cc65/expr.c [hunk 2]
```diff
@@ -2501,6 +2501,37 @@ static void hie_internal (const GenDesc* Ops,   /* List of generators */
                 }
             }
 
+            /* Limit the calculated value to the range of its type */
```
Comment (jmr) [inline src/cc65/expr.c:2504]: It looks like `+` and `-` are handled in `parseadd` and `parsesub`. Check everywhere `IVal` is assigned.

Comment (acqn) [reply src/cc65/expr.c:2504]: Nice catch. Fix for arithmetic `+` and `-` upcoming.

**Comment by acqn** [comment]
> 
> 
> What about unary operators? Can't `~` and `-` make unwanted high bits? (Maybe this is already handled somewhere for all I know.)

True. Example:
```c
    if (-32768U != 32768U) {
        fprintf (stderr, "Expected -32768U == 32768U, got: %ld\n", (long)-32768U);
        failures++;
    }
```

There might be obscure ones: `p[n]`, `s.a` and `s->b`, but I suppose they would already become UB in that case.

File: src/cc65/expr.c (hunk 1 above)
Comment (acqn) [reply src/cc65/expr.c:2508]: This should be a global static assertion, together with `sizeof (long) == 4`.

Comment (jmr) [reply src/cc65/expr.c:2508]: Apparently, this is supposed to compile with C89, so C11 is a bit out of the question.

I'm going to try to add `stdint.h`-like typedefs to `common/inttypes.h` and see if that gets merged. Then this can just be `int16_t`.

**Comment by acqn** [comment]
There are quite a few naive checks like `Expr->IVal < 0` that would be broken by a simple "always store a C correct value". The issue requires much more work than this.

**Comment by greg-king5** [comment]
> There are quite a few naive checks like `Expr->IVal < 0` that would be broken by a simple "always store a cc65-correct value" fix. The issue requires much more work than this.

`Expr->IVal = (signed short)Expr->IVal;` is evaluated as
`Expr->IVal = (signed long)(signed short)(signed long)Expr->IVal;`.  Won't normal sign extension handle negative-sign tests?

**Comment by jmr** [comment]
> There are quite a few naive checks like `Expr->IVal < 0` that would be broken by a simple "always store a C correct value" fix. The issue requires much more work than this.

Then maybe split out the pieces that can be submitted already, and put comments where things are wrong but break other places. Then we can pick those apart later.

File: src/cc65/expr.c (hunk 1 above)
Comment (jmr) [reply src/cc65/expr.c]: > This should be a global static assertion, together with `sizeof (long) == 4`.

I've been assuming the assumption was `sizeof(long) >= 4`. `sizeof(long) == 8` on most 64-bit platforms, AFAIK. Using `int32_t` would make this clear. #1326 adds these for C89 compilers.

Comment (acqn) [reply src/cc65/expr.c]: Resolved.

**Comment by acqn** [comment]
You are right. I think this is done right and can be merged now.

File: test/val/bug1310.c [hunk 3]
```diff
@@ -68,6 +68,21 @@ int main (void)
...
 
+    if (-32768U != 32768U) {
+        fprintf (stderr, "Expected -32768U == 32768U, got: %ld\n", (long)-32768U);
+        failures++;
+    }
+    if (~32767U != 32768U) {
+        fprintf (stderr, "Expected ~32767U == 32768U, got: %ld\n", (long)~32767U);
+        failures++;
+    }
     printf ("failures: %u\n", failures);
```
Comment (greg-king5) [inline test/val/bug1310.c:79]: A `printf()` is below the next test.  Therefore, this line must be removed (it's redundant).

File: test/val/bug1310.c [hunk 4]
```diff
@@ -68,6 +68,21 @@ int main (void)
...
+
+    if ((long*)0x1000 - (long*)0x2000 >= 0) {
+        fprintf (stderr, "Expected (long*)0x1000 - (long*)0x2000 < 0, got: %d\n", (long*)0x1000 - (long*)0x2000 >= 0);
```
Comment (greg-king5) [inline test/val/bug1310.c:82]: The third argument should be only the subtraction.  It shouldn't have the comparison.

File: test/val/bug1310.c (hunk 3 above)
Comment (acqn) [reply test/val/bug1310.c]: Fixed.

File: test/val/bug1310.c (hunk 4 above)
Comment (acqn) [reply test/val/bug1310.c]: Fixed.

**Review by greg-king5 — APPROVED** [review]
This looks good; merging.
