### PR TITLE
[cc65] Fixed constant boolean expressions

### LINKED ISSUE #250: Array size compile-time optimization stops halfway
The following file errors out on line 3. It compiles fine on gcc with -ansi -pedantic, which forces it to hard c89 mode.

```
#define LZO_MAX(a,b)        ((a) >= (b) ? (a) : (b))
unsigned char c[2*4];
unsigned char b[2*LZO_MAX(8,sizeof(int))];
```

### LINKED ISSUE #1123: "Result of comparison is constant" warning in constant expressions
`int x[0 == 0];` [gives the warning](https://godbolt.org/z/v3f45d):
```
<source>(1): Warning: Result of comparison is constant
```

This isn't a useful warning, since the expression here has to be a constant.

### LINKED ISSUE #1221: [cc65] Structs/unions as ternary operands
```c
int a;
struct S { int a; } s1, s2;
struct U { int a; } u1, u2;

int main()
{
    a ? s1 : s2; /* BUG: should be OK */
    a ? u1 : u2; /* BUG: should be OK */
    return 0;
}
```

### PR DESCRIPTION
**Pull request by acqn**
(8/8) commits.
- [x] Moved the almighty `bug250.c` from `test/misc` to `test/val`.
  - [x] Added integer boolean type string - no longer set the "expression tested" flag with constant results in comparison.
  - [x] Fixed #1123 - no more warnings on "const comparisons" that are desired in constant context.
  - [x] Warnings on expressions with no effects instead of statements with no effects.
  - [x] Fixed #250 (the OP part) - const ternary operator.
  - [x] Fixed #1221 - ternary couldn't use struct/union types as the true/false-branch expressions.
  - [x] Fixed #250 (https://github.com/cc65/cc65/issues/250#issuecomment-658003430) - logical AND and logical OR.
- [x] Added a constant AND/OR codegen test.

---
It might be worth mentioning that despite 1d7fcc67a498f65a4687099b87a40d402c039c78 saves nearly half of the labels, the new testcase d4025efaba798c652302bb49fb45506f8504b5c0 still easily reaches a big label number (>= L1131). The enhancements suggested in #301 might be desired.

### CODE REVIEW

**Comment by acqn** [comment]
I think I really hate `test/misc`.

**Comment by acqn** [comment]
Huh? So Travis CI doesn't respect the order in which the commits are pushed, but just reschedules the tests according to the "timestamps" of the commits? @oliverschmidt

**Comment by acqn** [comment]
I give up. Enjoy the commit fusion.

**Comment by acqn** [comment]
It seems to me that the "random" build failure tends to happen when there are multiple tests scheduled. I don't know if that indicates some hidden memory corruption bug since I can't reproduce it on my PC.

**Comment by oliverschmidt** [comment]
> Huh? So Travis CI doesn't respect the order in which the commits are pushed, but just reschedules the tests according to the "timestamps" of the commits? @oliverschmidt

Either I get you wrong or I'd be pretty surprised if it were as you describe. The picture I have in mind is that Travis CI doesn't know anything about Git. When something is pushed to the upstream repo, a test of what was pushed is triggered. However, If your experience contradicts my understanding then my understanding is likely wrong...

**Comment by jmr** [comment]
It says it builds the merge (so not exactly what was pushed if HEAD is different), but I'm not sure if that helps to explain anything.
https://docs.travis-ci.com/user/pull-requests/#how-pull-requests-are-built

**Comment by oliverschmidt** [comment]
> It seems to me that the "random" CI build failure (https://travis-ci.org/github/cc65/cc65/jobs/721197860) tends to happen when there are multiple tests scheduled. I don't know if that indicates some hidden memory corruption bug or not since I can't reproduce it on my PC.

I re-ran that Travis CI job quite some times. It succeeded each time.

**Comment by acqn** [comment]
> 
> 
> > It seems to me that the "random" CI build failure (https://travis-ci.org/github/cc65/cc65/jobs/721197860) tends to happen when there are multiple tests scheduled. I don't know if that indicates some hidden memory corruption bug or not since I can't reproduce it on my PC.
> 
> I re-ran that Travis CI job quite some times. It succeeded each time.

Could you re-run https://travis-ci.org/github/cc65/cc65/jobs/721079643?

**Comment by acqn** [comment]
> 
> 
> It says it builds the merge (so not exactly what was pushed if HEAD is different), but I'm not sure if that helps to explain anything.
> https://docs.travis-ci.com/user/pull-requests/#how-pull-requests-are-built

It appears to me that the CI "caches" the results of some _commits_ (instead of "merged snapshots") and reuses them without redoing the tests.

**Comment by acqn** [comment]
True order:
1. Added integer boolean type string. 17bbba7
2. Moved bug250.c from test/misc as it is to be fixed. b15ab34
3. Fixed warnings on const comparison. 3ea3887
4. Moved bug250.c from test/misc as it is to be fixed. b15ab34
5. Fixed constant expression checks with no-code requirement. 7255111
6. Fixed logical AND and logical OR. 85ea066
7. Avoided generating unnecessary true-case labels in logic AND/OR. f289ea6
8. Added test/ref/pr1220 for testing constant AND/OR code generation. b6a4715

**Comment by oliverschmidt** [comment]
> Could you re-run https://travis-ci.org/github/cc65/cc65/jobs/721079643? That one was weird that it fore-triggered a bug pushed after the commits it was testing.

I re-ran that Travis CI job quite some times. It succeeded each time.

**Comment by oliverschmidt** [comment]
> I give up. I don't want to fight test/misc, GitHub and Travis CI at the same time. 

If I understand things right, Travis CI entered the arena because the cc65 build wasn't fully parallelizable. Therefore I worked on that issue. I now closed https://github.com/cc65/cc65/issues/1080 and presume that you can therefore revert to a local build.

**Comment by acqn** [comment]
Could it be possible that the failed tests were caused by flawed cc65 executable builds? The only way a revision test could demonstrate a "future" bug would be:
1. There was a different hidden bug that could demenstrate exactly the same symptoms.
2. The test was indeed done with the future commit built into the executable.

File: src/cc65/datatype.c [hunk 1]
```diff
@@ -66,6 +66,7 @@ Type type_int[]         = { TYPE(T_INT),    TYPE(T_END) };
 Type type_uint[]        = { TYPE(T_UINT),   TYPE(T_END) };
 Type type_long[]        = { TYPE(T_LONG),   TYPE(T_END) };
 Type type_ulong[]       = { TYPE(T_ULONG),  TYPE(T_END) };
+Type type_bool[]        = { TYPE(T_INT),    TYPE(T_END) };
```
Comment (jmr) [inline src/cc65/datatype.c:69]: What should happen to `type_bool` if `_Bool` is introduced? Then it becomes `TYPE(T_INT)` or we just need to figure it out later?

File: src/cc65/exprdesc.h [hunk 2]
```diff
@@ -104,29 +104,58 @@ enum {
...
 
+    /* Expression evaluation requirements.
+    ** Usage: (Flags & E_EVAL_<Flag>) == E_EVAL_<Flag>
+    */
+    E_MASK_EVAL         = 0xFC0000,
+    E_EVAL_NONE         = 0x000000,     /* No requirements */
+    E_EVAL_CONST        = 0x040000,     /* Result must be immutable */
+    E_EVAL_COMPILE_TIME = 0x0C0000,     /* Result must be known at compile time */
+    E_EVAL_PURE         = 0x100000,     /* Evaluation must have no side effects */
+    E_EVAL_STATIC       = 0x340000,     /* Evaluation must generate no code */
```
Comment (jmr) [inline src/cc65/exprdesc.h:144]: I think having `STATIC` and `CONST` names that mean different things from `static` and `const` in C is a bit confusing.

File: src/cc65/expr.h [hunk 3]
```diff
@@ -54,23 +54,23 @@ int evalexpr (unsigned flags, void (*Func) (ExprDesc*), ExprDesc* Expr);
...
 ** printed, and the value is replaced by a constant one to make sure there
 ** are no internal errors that result from this input error.
 */
 
-void ConstAbsIntExpr (void (*Func) (ExprDesc*), ExprDesc* Expr);
-/* Will evaluate an expression via the given function. If the result is not
-** a constant numeric integer value, a diagnostic will be printed, and the
+ExprDesc StaticConstExpr (void (*Func) (ExprDesc*));
+/* Get an expression evaluated via the given function. If the result is not a
+** static constant expression, a diagnostic will be printed, and the value is
```
Comment (jmr) [inline src/cc65/expr.h:66]: What is a "static constant expression"? Explain or include pointers to which definitions of these terms you're using.

File: src/cc65/datatype.c (hunk 1 above)
Comment (acqn) [reply src/cc65/datatype.c:69]: It would use a new `T_BOOL` (that is  `T_TYPE_BOOL | T_CLASS_INT | T_SIGN_UNSIGNED | T_SIZE_BOOL`, and probably a `BOOL_BITS` that equals `1`. It would need special handling like `char` and `enum`.

File: src/cc65/expr.h (hunk 3 above)
Comment (acqn) [reply src/cc65/expr.h:66]: It could be read at the definition of `E_EVAL_C_CONST`. `Static` in such a context means "evaluated without any runtime code generated" as in #1196. What about changing the phrase
> static constant expression

to
> constant expression needing no runtime code

?

**Comment by oliverschmidt** [comment]
@acqn: Do you consider the two remarks from @jmr resolved? If yes, please mark them as such.

**Comment by acqn** [comment]
Not yet. I can rename them, but I haven't come up with good names.

File: src/cc65/exprdesc.h (hunk 2 above)
Comment (acqn) [reply src/cc65/exprdesc.h:144]: There have been different meanings of `const`/`constant` in cc65 for a long time, which I think should be enough to keep people aware of that. And `static` in C mostly refers to object linkage rather than expression traits, except for `_Static_assert`, which exactly indicates the same "no runtime" virtual as used here.

Anyways, do you have suggestions for better names? `E_EVAL_IMMUTABLE` could be  good for `E_EVAL_CONST`, but `E_EVAL_NO_CODE`, `E_EVAL_CODELESS` or `E_EVAL_EMPTY_CODE` for `E_EVAL_STATIC`?

Comment (jmr) [reply src/cc65/exprdesc.h:144]: I didn't realize, but many/most of these are currently unused.

It would definitely help to expand the comments. "must be immutable" doesn't tell me much. Is `(i++, 0)` immutable? Having good documentation is more important than getting the right names right now. 

`E_EVAL_NO_CODE` seems good for `E_EVAL_STATIC`. I'll try to think about the other names.

File: src/cc65/expr.h [hunk 4]
```diff
@@ -54,25 +54,25 @@ int evalexpr (unsigned flags, void (*Func) (ExprDesc*), ExprDesc* Expr);
...
 */
 
-void ConstAbsIntExpr (void (*Func) (ExprDesc*), ExprDesc* Expr);
-/* Will evaluate an expression via the given function. If the result is not
-** a constant numeric integer value, a diagnostic will be printed, and the
-** value is replaced by a constant one to make sure there are no internal
-** errors that result from this input error.
+ExprDesc StaticConstExpr (void (*Func) (ExprDesc*));
+/* Get an expression evaluated via the given function. If the result is not a
+** constant expression without runtime code generated, a diagnostic will be
```
Comment (jmr) [inline src/cc65/expr.h:66]: Can you say something like "constant expression as defined by `E_EVAL_...`?

File: src/cc65/exprdesc.h [hunk 5]
```diff
@@ -104,29 +104,58 @@ enum {
...
+    E_NEED_TEST         = 0x020000,     /* Expression needs a test to set cc */
 
+    /* Expression evaluation requirements.
+    ** Usage: (Flags & E_EVAL_<Flag>) == E_EVAL_<Flag>
+    */
+    E_MASK_EVAL         = 0xFC0000,
+    E_EVAL_NONE         = 0x000000,     /* No requirements */
+    E_EVAL_CONST        = 0x040000,     /* Result must be immutable */
+    E_EVAL_COMPILE_TIME = 0x0C0000,     /* Result must be known at compile time */
+    E_EVAL_PURE         = 0x100000,     /* Evaluation must have no side effects */
```
Comment (jmr) [inline src/cc65/exprdesc.h:143]: Pure usually means no side effects and same result for same inputs. `E_EVAL_NO_SIDE_EFFECTS` is a bit long, but `*p` isn't pure, is it?

File: src/cc65/exprdesc.h (hunk 2 above)
Comment (acqn) [reply src/cc65/exprdesc.h:144]: The comment says "**Result** must be immutable". The result of the expression `(i++, 0)` is always `0`. Thus it is immutable.

File: src/cc65/expr.h (hunk 4 above)
Comment (acqn) [reply src/cc65/expr.h:66]: What about both?

File: src/cc65/exprdesc.h (hunk 5 above)
Comment (acqn) [reply src/cc65/exprdesc.h:143]: The concept "Pure" was borrowed from "pure function" but it is about expressions, not just functions. It's true that the names could have better substitutes. I'll go with `E_EVAL_NO_SIDE_EFFECTS`.

**Comment by jmr** [comment]
Thanks! The new comments are helpful.

**Comment by acqn** [comment]
There was a potential subexpression issue in ternary operation similar to #1181. Now fixed in 74def4608aab0065d118e4a072e8aab9b6918cd6.

**Comment by acqn** [comment]
There were two bugs with 74def4608aab0065d118e4a072e8aab9b6918cd6. Incoming hotfix.
