### PR TITLE
WDM support

### LINKED ISSUE #715: WDM not supported by ca65
The table of instructions in src/ca65/instr.c doesn't have WDM in it.  This causes assembly to fail when it encounters something like "WDM $00":

    Checkcc.S(3): Error: `:' expected
    Checkcc.S(3): Error: Unexpected trailing garbage characters

The disassembler sources know about WDM, treating it similarly to COP.  src/da65/opc65816.c has:

```
    {   "cop",  2,  flNone,                   OH_Implicit              }, /* $02 */
   ....
    {   "wdm",  2,  flNone,                   OH_Implicit              }, /* $42 */
```

I would argue that the assembler should treat it the same way.

### PR DESCRIPTION
**Pull request by polluks**
Fixes  #715.

### CODE REVIEW

File: src/ca65/instr.c [hunk 1]
```diff
@@ -659,7 +659,7 @@ static const struct {
         { "CLI",  0x0000001, 0x58, 0, PutAll },
         { "CLV",  0x0000001, 0xb8, 0, PutAll },
         { "CMP",  0x0b8f6fc, 0xc0, 0, PutAll },
-        { "COP",  0x0000004, 0x02, 6, PutAll },
+        { "COP",  0x0000004, 0x02, 0, PutAll },
```
Comment (greg-king5) [inline src/ca65/instr.c]: That change will cause a bug that's similar to issue #716.
